# Generated by Django 5.0.7 on 2024-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('p', 'In Progress'), ('d', 'Done')], default='p', max_length=1),
        ),
    ]
